import { useState } from 'react';
import './App.css';

const products = [
  { id: 'core', name: 'Relic Wash Oversized Tee', colors: ['Black Wash', 'Grey Wash'], price: '349 MAD', image: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=1200&q=85', badge: 'BEST SELLER', description: 'A 350 GSM oversized tee with an OTHFIT original back print, dropped shoulders and a washed, lived-in finish.' },
  { id: 'essential', name: 'Forge Graphic Oversized Tee', colors: ['Brown Wash', 'Off White'], price: '349 MAD', image: 'https://images.unsplash.com/photo-1611312449408-fcece27cdbb7?auto=format&fit=crop&w=1200&q=85', badge: 'NEW', description: 'Heavyweight 100% cotton with an original OTHFIT graphic treatment and a structured oversized profile.' },
  { id: 'pump', name: 'Afterhours Pump Cover', colors: ['Grey Wash', 'Black Wash'], price: '369 MAD', image: 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=1200&q=85', description: 'A substantial 350 GSM pump cover built with wide shoulders, a durable collar and an original OTHFIT statement print.' },
  { id: 'heavy', name: 'Iron Relic Heavy Tee', colors: ['Black Wash', 'Brown Wash'], price: '349 MAD', image: 'https://images.unsplash.com/photo-1598032895397-b9472444bf93?auto=format&fit=crop&w=1200&q=85', description: 'Washed heavyweight cotton, a long relaxed sleeve and OTHFIT original artwork for a bold but wearable training layer.' },
  { id: 'motion', name: 'Monument Oversized Tee', colors: ['Off White', 'Grey Wash'], price: '349 MAD', image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=1200&q=85', description: 'A clean 350 GSM oversized tee with a soft-washed hand feel and original OTHFIT placement graphics.' },
  { id: 'everyday', name: 'Foundry Washed Tee', colors: ['Brown Wash', 'Black Wash'], price: '349 MAD', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=85', description: 'Premium heavyweight cotton and a relaxed drop-shoulder fit designed for training, rest days and repeat wear.' },
];

function Header({ home }) { return <><div className="announcement">FREE DELIVERY IN MOROCCO ON ORDERS OVER 600 MAD</div><header className="header fixed-header"><button className="icon-button menu-button" aria-label="Open menu"><span></span><span></span></button><button className="logo logo-button" onClick={home}>OTH<span>FIT</span></button><nav className="desktop-nav"><button onClick={home}>Top sellers</button><button onClick={home}>Men</button><button onClick={home}>Our standard</button></nav><div className="header-actions"><button className="icon-button search" aria-label="Search">+</button><button className="icon-button bag">Bag <sup>0</sup></button></div></header></>; }
function Card({ product, select }) { return <article className="product-card"><button className="product-button" onClick={() => select(product)}><div className="product-image-wrap">{product.badge && <span className="badge">{product.badge}</span>}<span className="quick-add">+</span><img src={product.image} alt={product.name} className="product-image" /></div><div className="product-details"><div><h3>{product.name}</h3><p>{product.colors[0]}</p></div><strong>{product.price}</strong></div></button></article>; }
function Collection({ title, eyebrow, items, id, select }) { return <section className="collection" id={id}><div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><a href={`#${id}`} className="text-link">View all <span>→</span></a></div><div className="product-grid">{items.map(product => <Card key={product.id} product={product} select={select} />)}</div></section>; }
function ProductPage({ product, home }) { const [color, setColor] = useState(product.colors[0]); const [size, setSize] = useState('M'); const [added, setAdded] = useState(false); return <main className="product-page"><button className="back-link" onClick={home}>← Back to shop</button><div className="product-layout"><div className="detail-image"><img src={product.image} alt={product.name} /></div><div className="product-info"><p className="eyebrow">OTHFIT MEN</p><h1>{product.name}</h1><p className="product-price">{product.price}</p><p className="product-description">{product.description}</p><div className="selector"><div className="selector-heading"><span>Color</span><b>{color}</b></div><div className="option-row">{product.colors.map((option, index) => <button key={option} onClick={() => setColor(option)} aria-label={option} className={`color-option color-${index} ${color === option ? 'selected' : ''}`}></button>)}</div></div><div className="selector"><div className="selector-heading"><span>Size</span><button className="size-guide">Size guide</button></div><div className="option-row sizes">{['S', 'M', 'L', 'XL'].map(option => <button key={option} onClick={() => setSize(option)} className={size === option ? 'selected' : ''}>{option}</button>)}</div></div><button className="add-button" onClick={() => setAdded(true)}>{added ? 'Added to bag' : `Add to bag — ${product.price}`}</button><div className="product-notes"><p>Premium heavyweight cotton</p><p>Free Morocco delivery over 600 MAD</p><p>Easy size exchange</p></div></div></div></main>; }
function Home({ select }) { return <main id="top"><section className="hero"><div className="hero-copy"><p className="eyebrow">BUILT FOR THE WORK</p><h1>Every rep.<br />Every day.</h1><p className="hero-text">Premium essentials engineered for the way you train.</p><a href="#top-sellers" className="button button-dark">Shop top sellers <span>→</span></a></div><div className="hero-image" role="img" aria-label="Athlete training in gymwear"></div><div className="hero-stamp"><span>PREMIUM</span><b>OTH<br />FIT</b><span>TRAINING GOODS</span></div></section><section className="assurances" id="about"><p><span>01</span> PREMIUM WEIGHT FABRICS</p><p><span>02</span> MADE TO MOVE</p><p><span>03</span> DESIGNED IN MOROCCO</p></section><Collection id="top-sellers" title="Top sellers" eyebrow="THE COMMUNITY CHOICE" items={products.slice(0, 3)} select={select} /><section className="dark-banner"><p className="eyebrow">OTHFIT STANDARD</p><p className="banner-quote">“No shortcuts.<br />Just better gear.”</p><span>EST. 2026 · MOROCCO</span></section><Collection id="men" title="Men's essentials" eyebrow="TRAIN WITH INTENT" items={products.slice(3)} select={select} /></main>; }
export default function App() { const [selected, setSelected] = useState(null); const home = () => { setSelected(null); window.scrollTo({ top: 0, behavior: 'smooth' }); }; return <div className="storefront"><Header home={home} />{selected ? <ProductPage product={selected} home={home} /> : <Home select={(product) => { setSelected(product); window.scrollTo(0, 0); }} />}<footer><button className="logo logo-button" onClick={home}>OTH<span>FIT</span></button><p>Premium training essentials. Built for your everyday discipline.</p><p className="copyright">© 2026 OTHFIT. ALL RIGHTS RESERVED.</p></footer></div>; }
